apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blockdeviceclaims.openebs.io
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.blockDeviceName
      name: BlockDeviceName
      type: string
    - JSONPath: .status.phase
      name: Phase
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: openebs.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: BlockDeviceClaim
    listKind: BlockDeviceClaimList
    plural: blockdeviceclaims
    shortNames:
      - bdc
    singular: blockdeviceclaim
