# Bind the Service Account with the Role Privileges.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-ndm-operator
  namespace: openebs
subjects:
  - kind: ServiceAccount
    name: openebs-maya-operator
    namespace: openebs
roleRef:
  kind: ClusterRole
  name: openebs-ndm-operator
  apiGroup: rbac.authorization.k8s.io
---
