# Create NDM node exporter daemonset.
# This is an optional component used for getting disk level
# metrics from each of the storage nodes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ndm-node-exporter
  namespace: openebs
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: ndm-node-exporter
  template:
    metadata:
      labels:
        name: ndm-node-exporter
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: node-disk-exporter
        image: openebs/node-disk-exporter:ci
        command:
        - /usr/local/bin/exporter
        args:
        - "start"
        - "--mode=node"
        - "--port==$(METRICS_LISTEN_PORT)"
        - "--metrics=/metrics"
        ports:
        - containerPort: 9101
          protocol: TCP
          name: metrics
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_LISTEN_PORT
          value: :9101
---
# Create NDM node exporter service
# This is optional and required only when
# ndm-node-exporter daemonset is used
apiVersion: v1
kind: Service
metadata:
  name: ndm-node-exporter-service
  labels:
    name: openebs-ndm-node-exporter
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
  selector:
    name: ndm-node-exporter
---
