# Create NDM cluster exporter deployment.
# This is an optional component and is not required for the basic
# functioning of NDM
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndm-cluster-exporter
  namespace: openebs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: ndm-cluster-exporter
  template:
    metadata:
      labels:
        name: ndm-cluster-exporter
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: ndm-cluster-exporter
        image: openebs/node-disk-exporter:ci
        command:
        - /usr/local/bin/exporter
        args:
        - "start"
        - "--mode=cluster"
        - "--port=$(METRICS_LISTEN_PORT)"
        - "--metrics=/metrics"
        ports:
        - containerPort: 9100
          protocol: TCP
          name: metrics
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_LISTEN_PORT
          value: :9100
---
# Create NDM cluster exporter service
# This is optional and required only when
# ndm-cluster-exporter deployment is used
apiVersion: v1
kind: Service
metadata:
  name: ndm-cluster-exporter-service
  labels:
    name: openebs-ndm-exporter
    component: openebs-ndm-cluster-exporter
  namespace: openebs
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    name: ndm-cluster-exporter
---
