apiVersion: openebs.io/v1alpha1
kind: BlockDevice
metadata:
  name: example-blockdevice
  labels:
    kubernetes.io/hostname: <host name in which disk/blockdevice is attached> # like gke-openebs-user-default-pool-044afcb8-bmc0
    ndm.io/managed: "false" # for manual disk creation put false
    ndm.io/disk-type: <blockdevice type> # like disk, partition, sparse file
status:
  claimState: Unclaimed
  state: Active
spec:
  capacity:
    logicalSectorSize: <logical sector size of lockdevice> # like 512
    storage: <total capacity in bits> #like 53687091200
  details:
    firmwareRevision: <firmware revision>
    model: <model name of blockdevice> # like PersistentDisk
    serial: <serial no of disk> # like google-disk-2
    compliance: <compliance of disk> #like "SPC-4"
    vendor: <vendor of disk> #like Google
  devlinks:
  - kind: by-id
    links:
    - <link1> # like /dev/disk/by-id/scsi-0Google_PersistentDisk_disk-2
    - <link2> # like /dev/disk/by-id/google-disk-2
  - kind: by-path
    links:
    - <link1> # like /dev/disk/by-path/virtio-pci-0000:00:03.0-scsi-0:0:2:0
  nodeAttributes:
    nodeName: <node name> # output of `kubectl get nodes` can be used
  partitioned: # Yes or No
  path: <devpath> # like /dev/sdb
