apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devicerequest.openebs.io
spec:
  group: openebs.io
  names:
    kind: DeviceRequest
    listKind: DeviceRequestList
    plural: devicerequests
    singular: devicerequest
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
