apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devices.openebs.io
spec:
  group: openebs.io
  names:
    kind: Device
    listKind: DeviceList
    plural: devices
    singular: device
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
