apiVersion: v2
name: openebs-ndm
description: Helm chart for OpenEBS Node Disk Manager - a Kubernetes native storage device management solution. For instructions on how to install, refer to https://openebs.github.io/node-disk-manager/.
version: 1.5.1
appVersion: 1.5.0
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - ndm
  - disk-inventory
  - storage
sources:
  - https://github.com/openebs/node-disk-manager
maintainers:
  - name: akhilerm
    email: akhil.mohan@mayadata.io
  - name: xUnholy
    email: michaelfornaro@gmail.com
  - name: prateekpandey14
    email: prateek.pandey@mayadata.io
