# Bind the Service Account with the Role Privileges.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-ndm
  namespace: default
  labels:
    app: openebs
subjects:
  - kind: ServiceAccount
    name: openebs-ndm
    namespace: default
  - kind: User
    name: system:serviceaccount:default:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: openebs-ndm
  apiGroup: rbac.authorization.k8s.io
